services:
  comfyui:
    image: saladtechnologies/comfyui:comfy0.2.2-api1.4.2-base
    volumes:
      - ./bin:/app/bin
    command: ["/app/bin/comfyui-api"]
    ports:
      - "3000:3000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
